title: I'm coding my life title
author: g-Log
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I thought I was not able to coding at begin
  But now I'm a bit more confident
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
